//mutation_types.js
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const CHANGE_MSG = 'CHANGE_MSG';
export const LOAD_GAME_LINES = 'LOAD_GAME_LINES';
export const LOADING_GAME = 'LOADING';
export const LOAD_GAME_TEASER = 'LOAD_GAME_TEASER';
export const ERROR = 'ERROR';
export const LOAD_PARLAY_GAME = 'LOAD_PARLAY_GAME';
export const LOAD_LIVE_EVENT_GAME = 'LOAD_LIVE_EVENT_GAME';
export const LOAD_SECTION_GAME = 'LOAD_SECTION_GAME';
export const LOAD_UPCOMING_EVENT = 'LOAD_UPCOMING_EVENT';